DECLARE
    AGE INTEGER;
BEGIN
    AGE := &AGE;
    -- CHECK WEATHER ELIGIBLE FOR VOTING --> 18
    IF (AGE >= 18) THEN 
        DBMS_OUTPUT.PUT_LINE('HE IS ELIGIBLE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('HE IS NOT ELIGIBLE');
    END IF;
    
END;
/
